title: "Sridevi Blogs"
email: ""
description: >-
  A DevOps blog focused on real-world learning and career growth — by Sridevi Velpula.
baseurl: ""
url: "https://srideviblogs.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "sunrise"

author:
  name: "Sridevi Velpula"
  bio: "DevOps Engineer | Cloud Enthusiast | Turning Challenges into Opportunities — Empowering Growth and Innovation"

nav:
  - title: "Home"
    url: /
  - title: "Blog"
    url: /blog/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      css: "assets/css/custom.css"
