title: "Sridevi Blogs"
description: "A DevOps blog focused on real-world learning and career growth — by Sridevi Velpula."
baseurl: "" 
url: "https://sridevivelpula.github.io"

author:
  name: "Sridevi Velpula"
  github: srideviblogs
  linkedin: "https://www.linkedin.com/in/sandeep-pochu-27589b274/"
  location: "Santa Clara, CA"
  bio: "DevOps Engineer | Blogger | Tech Enthusiast"
logo: https://srideviblogs.github.io/assets/images/social-preview.png

# Permalink style - you can keep this or change if you want dated URLs
permalink: /:title/

paginate: 5
paginate_path: "/page:num/"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

collections:
  posts:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Blogs"
    url: "/blogs/"
  - title: "Categories"
    url: "/categories/"

google_analytics: ""  # Optional – replace with your ID
disqus: ""             # Optional – replace with your shortname

# Social Links (optional)
social:
  github: "https://github.com/sridevivelpula"
  linkedin: "https://www.linkedin.com/in/sandeep-pochu-27589b274/"

# Build settings (Important)
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor", "README.md"]
